# Generated by Django 2.0.6 on 2018-06-19 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='updated_at',
        ),
    ]
